# Generated by Django 5.0.7 on 2025-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, default='2000-01-01', help_text='Enter your birth date', null=True, verbose_name='Birth Date'),
        ),
    ]
