# Generated by Django 5.0.7 on 2025-01-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
