# Generated by Django 5.0.7 on 2025-01-17 17:08

import django.core.validators
import users.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_profileinterest_profilesociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB, formats: jpg, jpeg, png, gif)', null=True, upload_to='profile_pics/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), users.models.profile.validate_image_size]),
        ),
    ]
